puts "The students of Villains Academy"
puts "-----------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Wich of the West"
puts "Therminator"
puts "The Joker"
puts "Joffery Bartheon"
puts "Norman Bates"
